version: "3"
services:
  hermes:
    build: ./
    links:
      - mariadb
    depends_on:
      - mariadb
    environment:
      FLASK_ENV: PRODUCTION
      FLASK_DEBUG: 1
    ports:
      - "5000:5000"
    restart: on-failure

  mariadb:
    image: mariadb:10.4
    environment:
      MYSQL_ROOT_PASSWORD: hermes
      MYSQL_DATABASE: hermes
      MYSQL_USER: hermes
      MYSQL_PASSWORD: hermes
    restart: on-failure
